dataset_name: "jsb_piano"
dataset_params:
  subseq_len: 64
  batch_size: 64

model_name: "DMMBinary"
model_params:
  latent_dim: 100
  obs_dim: 88
  st_net_hidden_dim: 400
  st_net_n_layers: 1
  emission_hidden_size: 100
  transition_hidden_size: 200

loss_name: "DMMBinaryELBO"
loss_params:
  annealing_params:
    enabled: True
    warm_up: 50 # How many epochs before start adding KL term
    n_epochs_for_full: 30 # How many epochs to reach full KL term (will have weight 1 at this value + warmup)

trainer_name: "DeepTrainer"
trainer_params:
  n_epochs: 1000
  lr: 0.001
  val_freq: 10 # Validate every 10 epochs
  save_path: "models/dmm/jsb.pth"
  device: "cuda"
  verbose: False
  eval_window_shifts: [0,1,2,3,4,5]
  n_eval_windows: 5 # How many times to shift the window (starting from the end) for evaluation
  
logger_name: "PrintLogger"
logger_params: {}

