dataset_name: "linear_gssm"
dataset_params:
  n_time_steps: 25
  n_train_samples: 5000
  n_val_samples: 512
  n_test_samples: 512
  batch_size: 256
  return_times: True

model_name: "SDEContinuousFixedEmission"
model_params:
  n_euler_steps: 10
  transition_hidden_size: 32

loss_name: "SDEContinuousELBO"
loss_params:
  annealing_params:
    enabled: True
    warm_up: 1 # How many epochs before start adding KL term
    n_epochs_for_full: 100 # How many epochs to reach full KL term (will have weight 1 at this value + warmup)
  clipping_params:
    enabled: True
    clip_max: 10000.0
    clip_min: 1.0
  entropy_weight: 0.4
  entropy_q_weight: 0.0
  elog_weight: 0.6
  n_entropy_samples: 10

trainer_name: "DeepTrainer"
trainer_params:
  n_epochs: 150
  lr: 0.001
  val_freq: 10 # Validate every 10 epochs
  save_path: "models/sde/linear_synthetic/fixed_emission.pth"
  device: "cuda"
  verbose: False
  eval_window_shifts: [0,1,2,3,4,5]
  n_eval_windows: 5 # How many times to shift the window (starting from the end) for evaluation
  
logger_name: "WandbLogger"
logger_params: {}

