dataset_name: "jsb_piano"
dataset_params:
  subseq_len: 64
  batch_size: 32

model_name: "DMMBinary"
model_params:
  latent_dim: 400
  obs_dim: 88
  st_net_hidden_dim: 512
  st_net_n_layers: 4

loss_name: "DMMBinaryELBO"
loss_params:
  annealing_params:
    enabled: True
    warm_up: 3 # How many epochs before start adding KL term
    n_epochs_for_full: 15 # How many epochs to reach full KL term (will have weight 1 at this value + warmup)

trainer_name: "DeepTrainer"
trainer_params:
  n_epochs: 25
  lr: 0.0005
  val_freq: 10 # Validate every 10 epochs
  save_path: "models/dmm/jsb.pth"
  device: "cuda"
  verbose: False
  eval_window_shifts: [0,1,2,3,4,5]
  n_eval_windows: 5 # How many times to shift the window (starting from the end) for evaluation
  
logger_name: "PrintLogger"
logger_params: {}

