dataset_name: "physionet"
dataset_params:
  train_frac: 0.8
  val_frac: 0.1
  test_frac: 0.1
  imputation_method: "mean" # ["mean", "forward", "missing (fill with -1)", "linear_interpolation"]
  discretization_method: "none" # ["none", "integer (# of minutes)"]
  time_in_data: True
  return_times: False
  missing_in_data: False
  return_missing_mask: True
  batch_size: 128

model_name: "DMMContinuous"
model_params:
  st_net_hidden_dim: 256
  st_net_n_layers: 2
  latent_dim: 100
  obs_dim: 38

loss_name: "DMMContinuousELBO"
loss_params:
  rmse_eval_latent: False
  annealing_params:
    enabled: True
    warm_up: 50 # How many epochs before start adding KL term
    n_epochs_for_full: 50 # How many epochs to reach full KL term (will have weight 1 at this value + warmup)

trainer_name: "DeepTrainer"
trainer_params:
  n_epochs: 1000
  lr: 0.0005
  val_freq: 10 # Validate every 10 epochs
  save_path: "models/dmm/physionet.pth"
  device: "cuda"
  verbose: False
  eval_window_shifts: [0, 1, 3, 5]
  n_eval_windows: 5 # How many times to shift the window (starting from the end) for evaluation
  
logger_name: "WandbLogger"
logger_params: {}

